#!/bin/bash
../bin/strip-docker-image -i haproxy -t stripped-haproxy  \
	-x 80 \
	-f /usr/local/sbin/haproxy \
	-f /usr/local/etc/haproxy \
	-f /etc/passwd \
	-f /etc/group \
	-f '/lib/*/libnss*' \
	-f /bin/ls \
	-f /bin/cat \
	-f /bin/sh \
	-f /bin/mkdir \
	-f /bin/ps 
		
