#!/bin/bash

echo "SOURCE_COMMIT: $SOURCE_COMMIT"

if [[ -z "$SOURCE_COMMIT" ]]; then
	export SOURCE_COMMIT="${SOURCE_COMMIT:-$(git rev-parse HEAD)}"
	echo "Updating SOURCE_COMMIT from git rev-parse HEAD"
	echo "SOURCE_COMMIT: $SOURCE_COMMIT"
fi

IMAGE_NAME="${IMAGE_NAME:-imazen/imageflow_base_os}"

echo "DOCKER_TAG: $DOCKER_TAG"

docker build -t "$IMAGE_NAME" --build-arg "BASE_OS_SOURCE_COMMIT=$SOURCE_COMMIT" --build-arg "BASE_OS_DOCKER_TAG=$DOCKER_TAG" .